name: Run Test Suite

on: push

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 3,2
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.x

      - name: Install system dependencies
        run: |
          sudo apt-get install libsqlite3-dev

      - name: Bundle
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Running test suite
        run: |
          bundle exec rspec
